/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./pages/__root"
import { Route as MainLayoutRouteImport } from "./pages/_main-layout"
import { Route as LayoutRouteImport } from "./pages/_layout"
import { Route as AuthRouteImport } from "./pages/_auth"
import { Route as MainLayoutIndexRouteImport } from "./pages/_main-layout/index"
import { Route as AuthLoginRouteImport } from "./pages/_auth/login"
import { Route as LayoutRestaurantsRestaurantIdIndexRouteImport } from "./pages/_layout/restaurants.$restaurantId/index"
import { Route as LayoutFitnessFitnessIdIndexRouteImport } from "./pages/_layout/fitness.$fitnessId/index"
import { Route as LayoutRestaurantsRestaurantIdEmployeesRouteImport } from "./pages/_layout/restaurants.$restaurantId/employees"
import { Route as LayoutRestaurantsRestaurantIdCalendarRouteImport } from "./pages/_layout/restaurants.$restaurantId/calendar"
import { Route as LayoutFitnessFitnessIdEmployeesRouteImport } from "./pages/_layout/fitness.$fitnessId/employees"
import { Route as LayoutFitnessFitnessIdCalendarRouteImport } from "./pages/_layout/fitness.$fitnessId/calendar"

const MainLayoutRoute = MainLayoutRouteImport.update({
  id: "/_main-layout",
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: "/_layout",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: "/_auth",
  getParentRoute: () => rootRouteImport,
} as any)
const MainLayoutIndexRoute = MainLayoutIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => MainLayoutRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => AuthRoute,
} as any)
const LayoutRestaurantsRestaurantIdIndexRoute =
  LayoutRestaurantsRestaurantIdIndexRouteImport.update({
    id: "/restaurants/$restaurantId/",
    path: "/restaurants/$restaurantId/",
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutFitnessFitnessIdIndexRoute =
  LayoutFitnessFitnessIdIndexRouteImport.update({
    id: "/fitness/$fitnessId/",
    path: "/fitness/$fitnessId/",
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutRestaurantsRestaurantIdEmployeesRoute =
  LayoutRestaurantsRestaurantIdEmployeesRouteImport.update({
    id: "/restaurants/$restaurantId/employees",
    path: "/restaurants/$restaurantId/employees",
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutRestaurantsRestaurantIdCalendarRoute =
  LayoutRestaurantsRestaurantIdCalendarRouteImport.update({
    id: "/restaurants/$restaurantId/calendar",
    path: "/restaurants/$restaurantId/calendar",
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutFitnessFitnessIdEmployeesRoute =
  LayoutFitnessFitnessIdEmployeesRouteImport.update({
    id: "/fitness/$fitnessId/employees",
    path: "/fitness/$fitnessId/employees",
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutFitnessFitnessIdCalendarRoute =
  LayoutFitnessFitnessIdCalendarRouteImport.update({
    id: "/fitness/$fitnessId/calendar",
    path: "/fitness/$fitnessId/calendar",
    getParentRoute: () => LayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  "/login": typeof AuthLoginRoute
  "/": typeof MainLayoutIndexRoute
  "/fitness/$fitnessId/calendar": typeof LayoutFitnessFitnessIdCalendarRoute
  "/fitness/$fitnessId/employees": typeof LayoutFitnessFitnessIdEmployeesRoute
  "/restaurants/$restaurantId/calendar": typeof LayoutRestaurantsRestaurantIdCalendarRoute
  "/restaurants/$restaurantId/employees": typeof LayoutRestaurantsRestaurantIdEmployeesRoute
  "/fitness/$fitnessId": typeof LayoutFitnessFitnessIdIndexRoute
  "/restaurants/$restaurantId": typeof LayoutRestaurantsRestaurantIdIndexRoute
}
export interface FileRoutesByTo {
  "/login": typeof AuthLoginRoute
  "/": typeof MainLayoutIndexRoute
  "/fitness/$fitnessId/calendar": typeof LayoutFitnessFitnessIdCalendarRoute
  "/fitness/$fitnessId/employees": typeof LayoutFitnessFitnessIdEmployeesRoute
  "/restaurants/$restaurantId/calendar": typeof LayoutRestaurantsRestaurantIdCalendarRoute
  "/restaurants/$restaurantId/employees": typeof LayoutRestaurantsRestaurantIdEmployeesRoute
  "/fitness/$fitnessId": typeof LayoutFitnessFitnessIdIndexRoute
  "/restaurants/$restaurantId": typeof LayoutRestaurantsRestaurantIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/_auth": typeof AuthRouteWithChildren
  "/_layout": typeof LayoutRouteWithChildren
  "/_main-layout": typeof MainLayoutRouteWithChildren
  "/_auth/login": typeof AuthLoginRoute
  "/_main-layout/": typeof MainLayoutIndexRoute
  "/_layout/fitness/$fitnessId/calendar": typeof LayoutFitnessFitnessIdCalendarRoute
  "/_layout/fitness/$fitnessId/employees": typeof LayoutFitnessFitnessIdEmployeesRoute
  "/_layout/restaurants/$restaurantId/calendar": typeof LayoutRestaurantsRestaurantIdCalendarRoute
  "/_layout/restaurants/$restaurantId/employees": typeof LayoutRestaurantsRestaurantIdEmployeesRoute
  "/_layout/fitness/$fitnessId/": typeof LayoutFitnessFitnessIdIndexRoute
  "/_layout/restaurants/$restaurantId/": typeof LayoutRestaurantsRestaurantIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/login"
    | "/"
    | "/fitness/$fitnessId/calendar"
    | "/fitness/$fitnessId/employees"
    | "/restaurants/$restaurantId/calendar"
    | "/restaurants/$restaurantId/employees"
    | "/fitness/$fitnessId"
    | "/restaurants/$restaurantId"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/login"
    | "/"
    | "/fitness/$fitnessId/calendar"
    | "/fitness/$fitnessId/employees"
    | "/restaurants/$restaurantId/calendar"
    | "/restaurants/$restaurantId/employees"
    | "/fitness/$fitnessId"
    | "/restaurants/$restaurantId"
  id:
    | "__root__"
    | "/_auth"
    | "/_layout"
    | "/_main-layout"
    | "/_auth/login"
    | "/_main-layout/"
    | "/_layout/fitness/$fitnessId/calendar"
    | "/_layout/fitness/$fitnessId/employees"
    | "/_layout/restaurants/$restaurantId/calendar"
    | "/_layout/restaurants/$restaurantId/employees"
    | "/_layout/fitness/$fitnessId/"
    | "/_layout/restaurants/$restaurantId/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LayoutRoute: typeof LayoutRouteWithChildren
  MainLayoutRoute: typeof MainLayoutRouteWithChildren
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_main-layout": {
      id: "/_main-layout"
      path: ""
      fullPath: ""
      preLoaderRoute: typeof MainLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_layout": {
      id: "/_layout"
      path: ""
      fullPath: ""
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_auth": {
      id: "/_auth"
      path: ""
      fullPath: ""
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_main-layout/": {
      id: "/_main-layout/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof MainLayoutIndexRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    "/_auth/login": {
      id: "/_auth/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    "/_layout/restaurants/$restaurantId/": {
      id: "/_layout/restaurants/$restaurantId/"
      path: "/restaurants/$restaurantId"
      fullPath: "/restaurants/$restaurantId"
      preLoaderRoute: typeof LayoutRestaurantsRestaurantIdIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    "/_layout/fitness/$fitnessId/": {
      id: "/_layout/fitness/$fitnessId/"
      path: "/fitness/$fitnessId"
      fullPath: "/fitness/$fitnessId"
      preLoaderRoute: typeof LayoutFitnessFitnessIdIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    "/_layout/restaurants/$restaurantId/employees": {
      id: "/_layout/restaurants/$restaurantId/employees"
      path: "/restaurants/$restaurantId/employees"
      fullPath: "/restaurants/$restaurantId/employees"
      preLoaderRoute: typeof LayoutRestaurantsRestaurantIdEmployeesRouteImport
      parentRoute: typeof LayoutRoute
    }
    "/_layout/restaurants/$restaurantId/calendar": {
      id: "/_layout/restaurants/$restaurantId/calendar"
      path: "/restaurants/$restaurantId/calendar"
      fullPath: "/restaurants/$restaurantId/calendar"
      preLoaderRoute: typeof LayoutRestaurantsRestaurantIdCalendarRouteImport
      parentRoute: typeof LayoutRoute
    }
    "/_layout/fitness/$fitnessId/employees": {
      id: "/_layout/fitness/$fitnessId/employees"
      path: "/fitness/$fitnessId/employees"
      fullPath: "/fitness/$fitnessId/employees"
      preLoaderRoute: typeof LayoutFitnessFitnessIdEmployeesRouteImport
      parentRoute: typeof LayoutRoute
    }
    "/_layout/fitness/$fitnessId/calendar": {
      id: "/_layout/fitness/$fitnessId/calendar"
      path: "/fitness/$fitnessId/calendar"
      fullPath: "/fitness/$fitnessId/calendar"
      preLoaderRoute: typeof LayoutFitnessFitnessIdCalendarRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface LayoutRouteChildren {
  LayoutFitnessFitnessIdCalendarRoute: typeof LayoutFitnessFitnessIdCalendarRoute
  LayoutFitnessFitnessIdEmployeesRoute: typeof LayoutFitnessFitnessIdEmployeesRoute
  LayoutRestaurantsRestaurantIdCalendarRoute: typeof LayoutRestaurantsRestaurantIdCalendarRoute
  LayoutRestaurantsRestaurantIdEmployeesRoute: typeof LayoutRestaurantsRestaurantIdEmployeesRoute
  LayoutFitnessFitnessIdIndexRoute: typeof LayoutFitnessFitnessIdIndexRoute
  LayoutRestaurantsRestaurantIdIndexRoute: typeof LayoutRestaurantsRestaurantIdIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutFitnessFitnessIdCalendarRoute: LayoutFitnessFitnessIdCalendarRoute,
  LayoutFitnessFitnessIdEmployeesRoute: LayoutFitnessFitnessIdEmployeesRoute,
  LayoutRestaurantsRestaurantIdCalendarRoute:
    LayoutRestaurantsRestaurantIdCalendarRoute,
  LayoutRestaurantsRestaurantIdEmployeesRoute:
    LayoutRestaurantsRestaurantIdEmployeesRoute,
  LayoutFitnessFitnessIdIndexRoute: LayoutFitnessFitnessIdIndexRoute,
  LayoutRestaurantsRestaurantIdIndexRoute:
    LayoutRestaurantsRestaurantIdIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

interface MainLayoutRouteChildren {
  MainLayoutIndexRoute: typeof MainLayoutIndexRoute
}

const MainLayoutRouteChildren: MainLayoutRouteChildren = {
  MainLayoutIndexRoute: MainLayoutIndexRoute,
}

const MainLayoutRouteWithChildren = MainLayoutRoute._addFileChildren(
  MainLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LayoutRoute: LayoutRouteWithChildren,
  MainLayoutRoute: MainLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
